### ISSUE TITLE
Large unused dependencies

### ISSUE THREAD

**Issue by kjvalencik** [oleksiyk/kafka#209]
The following dependencies are not used and add considerable size. Typescript alone adds 23MB.

```js
buffer-cfc32
@types/lodash
@types/bluebird
typescript
```

Also, is it critical that lodash be locked to a specific version? It is preventing deduplication and is also fairly heavy (5M).

**Comment by oleksiyk** [comment]
- buffer-crc32 (not buffer-cfc32) is used in the library
- can't say anything about typescripts deps as I'm simply merging other PRs related to Typescript changes
- loads is locked because previously it caused several hard to debug problems with buffers, arrays and something else. Several times. So its locked to well known working version.

**Comment by kjvalencik** [comment]
Ah, typod my grep. Whoops. Typescript is the big one. I don't use to, so I'm not sure, but I think it can be removed.

**Comment by sharathbaddam** [comment]
I tested my producer by deleting 'typescript' node modules and dint notice any problems.

Also typescript is not used anywhere in code. I think we can remove it from dependencies list in package.json.

**Comment by oleksiyk** [comment]
@phreed is it safe to remove `typescript` from no-kafka dependencies?

**Comment by phreed** [comment]
@oleksiyk  it should not be needed. If someone is doing typescript development then their own project should require it. I do not recall if the test suite exercises the typescript capability or not.

**Comment by oleksiyk** [comment]
`typescript` removed in 3.2.7
