### ISSUE TITLE
Error Handling / Reconnect

### ISSUE THREAD

**Issue by margant** [oleksiyk/kafka#41]
Thanks for the awesome library!

Question applies for both Publisher and Subscriber. What would be the best way to:
1) Handle Errors (connection drop, network failure)
2) Reconnect on Error (or check connection every xxx period)

**Comment by oleksiyk** [comment]
All network errors are handled by a library and there is no need to check connection every X period:

- simple consumer periodically runs fetch request, if it fails due to network error then the library will reconnect and retry
- group consumer also does periodical heartbeats and handles all connection errors
- producer will reconnect and retry failed requests configurable about of times for each produce request
