### ISSUE TITLE
Producer retry logic does not preserve order (during a leader failure/election)

### ISSUE THREAD

**Issue by jotto** [oleksiyk/kafka#63]
## Steps to reproduce
1. start 2 kafka brokers (ports 9092, 9093)
2. create `mytopic` with replication-factor of 2

     ```bash
     ./bin/kafka-topics.sh --zookeeper localhost --topic mytopic --create --partitions 1 --replication-factor 2
     ```
3. start a consumer in a loop

     ```javascript
     var consumer = new Kafka.SimpleConsumer({connectionString: 'localhost:9092, localhost:9093'})
     consumer.init().then(function () {
       consumer.subscribe('mytopic', [], function (messageSet, topic, partition) {
         messageSet.forEach(function (m) {
           console.log(topic, partition, m.offset, m.message.value.toString('utf8'));
         });
       });
     });
     ```

4. configure `no-kafka` producer with max attempts and delay long enough to survive rebalancing

     ```javascript
     var producer = new NoKafka.Producer({
       connectionString: 'localhost:9092, localhost:9093',
       clientId: 'producer',
       timeout: 100,
       retries: {
           attempts: 10,
           delay: 1000
       }
     });
     ```

5. run `no-kafka` producer in loop

     ```javascript
     var counter = 0;
     setInterval(function() {
       producer.send({
           topic: 'mytopic',
           message: { value: 'message #' + counter },,
           partition: 0
       })
       .catch(function(err) { console.log('promise rejection', err); })
       .then(function(err) { console.log('promise fulfillment', err.error); });
     }, 1000)
     ```
6. `kill -9` whichever broker is the leader for `mytopic:0`
7. Observe the messages be sent in reverse order when the new leader is elected

![image](https://cloud.githubusercontent.com/assets/16573/15303960/7a9e0e0c-1b6f-11e6-99ac-b6139d9ee948.png)

**Comment by oleksiyk** [comment]
It happens because each message is sent and thus retried individually, each in its own `delay and attempt` loop. You are also not waiting for the previous message to be successfully fulfilled before sending next one. This scenario quite possibly can result in random order as well. Of course it sounds bad, but consider the following scenario:

- message M0 is followed by message M1 (M1 is sent after 1000 ms since M0 was sent)
- message M0 is destined to Broker0, M1 to Broker1
- Broker0 dies before M0 reached it
- message M0 is now retried in a loop, for 10  seconds
- message M1 is successfully delivered
- the order is reversed

**Comment by oleksiyk** [comment]
So you can only expect the messages to be received by Kafka in a specific order when you wait for successful delivery confirmation for each message before sending next one. Otherwise, even in a fully connected Kafka cluster the latency of different brokers can result in message reorder.
