### ISSUE TITLE
When connection disappears the `retries` option is not taken into account

### ISSUE THREAD

**Issue by koresar** [oleksiyk/kafka#64]
When connection disappears or if never was on the first place then the `NoKafkaConnectionError` is thrown.
`ERROR no-kafka-client Metadata request failed: NoKafkaConnectionError [127.0.0.1:9092]: Error: connect ECONNREFUSED`

The `retries.delay` and `retries.attempts` are not used in that case. The default `1000` value is used instead.
https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L155

Can submit a PR which uses the delay provided in the Producer options. Otherwise, please fix. Thanks!

**Comment by oleksiyk** [comment]
`Producer.send` retries option has no relation to the `Client.metadataRequest` (`Client` instance is also shared by GroupConsumer, GroupAdmin and etc). By design `Client.metadataRequest` has an endless loop trying to reach initial brokers. It can't use any limited number of attempts because otherwise the library will loose its state (more important for consumers, not for producers).

**Comment by koresar** [comment]
Can it be customizable at least?

**Comment by oleksiyk** [comment]
`reconnectionDelay` option is available in 2.5.0: https://github.com/oleksiyk/kafka/commit/76285190e535c7da51f71c98f1203efcab3527d1

**Comment by koresar** [comment]
Amazing news! Thank you Oleksiy.

**Comment by bviswana101** [comment]
Producer._send calls updateMetadataRequest() on retry and this goes into infinite loop when NoKafkaConnectionError is thrown from client.js:produceRequest. 

So, effectively, producer never gets an error on a send, when retries > 1.

Is there any way for the producer.send to return an error on Kafka errors instead of infinite looping?

**Comment by oleksiyk** [comment]
@bviswana101 there is no way to get out of reconnection loop.

**Comment by agouz** [comment]
@oleksiyk Can `reconnectionDelay` option be set for the producer.init() ?

**Comment by oleksiyk** [comment]
@agouz  `reconnectionDelay` is a library option, it applies to both producer and consumer.

**Comment by agouz** [comment]
@oleksiyk Thanks for replying. How can I set it so the producer.init() pick it up? currently it runs in an endless loop coz of invalid kafka url.

**Comment by oleksiyk** [comment]
I think all options are well documented in a README:

```javascript
var producer = new Kafka.Producer({
    reconnectionDelay: {
        min: 1000,
        max: 10000
    }
});
```

**Comment by bviswana101** [comment]
FYI: i got around the endless loop issue, by using bluebird Promise.timeout() option.

**Comment by koresar** [comment]
It would be great to have an event emitter which would fire when connection
established or lost.
